name: build-and-test

on:
  push:
    # all branches
  pull_request:
    # all branches

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Open Dylan
        uses: dylan-lang/install-opendylan@v3

      - name: Install Dependencies
        run: deft update

      - name: Build and Run Tests
        run: |
          mkdir -p _build  # can't redirect without it
          deft test -- --progress none --report surefire > _build/TEST-base64.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: '**/_build/TEST-*.xml'
